In [ ]:
going to analysis the netfix data set 

importing the libraries

In [3]:
import numpy as np
import pandas as pd

In [1]:
import numpy as np
import pandas as pd
netflix=pd.read_csv('data_netflix (2).csv')
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [2]:
#head - first 5 lines of column displayed 
netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [3]:
#head - last 5 lines of column displayed
netflix.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [4]:
#Get the general information about the dataframe
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6234 entries, 0 to 6233
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       6234 non-null   int64
 1   type          6234 non-null   object
 2   title         6234 non-null   object
 3   director      4265 non-null   object
 4   cast          5664 non-null   object
 5   country       5758 non-null   object
 6   date_added    6223 non-null   object
 7   release_year  6234 non-null   int64
 8   rating        6224 non-null   object
 9   duration      6234 non-null   object
 10  listed_in     6234 non-null   object
 11  description   6234 non-null   object
dtypes: int64(2), object(10)
memory usage: 584.6+ KB

In [5]:
netflix.index

RangeIndex(start=0, stop=6234, step=1)

In [6]:
netflix.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [7]:
netflix.loc[4757]

show_id                                                  80204119
type                                                        Movie
title                Baahubali: The Beginning (Malayalam Version)
director                                           S.S. Rajamouli
cast            Prabhas, Rana Daggubati, Anushka Shetty, Taman...
country                                                     India
date_added                                         August 7, 2017
release_year                                                 2015
rating                                                      TV-14
duration                                                  160 min
listed_in        Action & Adventure, Dramas, International Movies
description     Villagers in the kingdom of Mahismati rescue a...
Name: 4757, dtype: object

In [8]:
netflix['release_year'].min()

1925

In [9]:
netflix['release_year'].max()

2020

In [10]:
netflix['release_year'].idxmin()

4292

In [11]:
netflix.iloc[4292]

show_id                                                  81030762
type                                                      TV Show
title                           Pioneers: First Women Filmmakers*
director                                                      NaN
cast                                                          NaN
country                                                       NaN
date_added                                      December 30, 2018
release_year                                                 1925
rating                                                      TV-PG
duration                                                 1 Season
listed_in                                                TV Shows
description     This collection restores films from women who ...
Name: 4292, dtype: object

In [12]:
size=len(netflix['title'])
size

6234

In [13]:
netflix.drop('title',axis=1)

,show_id,type,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6231,80116008,Movie,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...
6232,70281022,TV Show,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6233,70153404,TV Show,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [14]:
netflix.drop('type',axis=1,inplace=True)

In [15]:
netflix

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6231,80116008,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...
6232,70281022,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6233,70153404,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

# Unfortunately there are no IMDB ratings in the dataset

We will create a random array 0 to 10 which has the same size to insert into the DataFrame as 'IMDB Rating'.

In [18]:
import numpy as np
import pandas as pd
imdb=np.random.uniform(low=0,high=10,size=len(netflix['title']))
imdb=np.around(imdb,decimals=1)

In [23]:
netflix['imdb Rating']=imdb
netflix

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,imdb Rating
0,81145628,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...,9.2
1,80117401,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,3.5
2,70234439,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",2.5
3,80058654,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,5.5
4,80125979,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil...",3.4
6230,70286564,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews...",2.7
6231,80116008,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...,0.1
6232,70281022,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ...",5.6
6233,70153404,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...,2.3

In [37]:
netflix[netflix['imdb Rating']==1.0].count()

show_id         54
title           54
director        36
cast            46
country         51
date_added      54
release_year    54
rating          54
duration        54
listed_in       54
description     54
imdb Rating     54
dtype: int64

# Find items with 9.9imdb rating and display only their title

In [36]:
netflix[netflix['imdb Rating']==9.9]['title']

257                                            Bleach
376                                       Little Evil
426       Winter on Fire: Ukraine's Fight for Freedom
453                         YG Future Strategy Office
489                                    Cult of Chucky
658                                  Verses of Love 2
665                                   Another Miss Oh
682                               Beasts of No Nation
766                                            اشتباك
822                                          Sin City
943                                         I Am Bolt
1016                                 The Desert Bride
1037                                 Tune in for Love
1154                                         De Palma
1241                                 Silvana Sin Lana
1344                                              187
1378                              Holiday in the Wild
1860                                  Pocoyo Carnival
1868                                        Sometimes
2164                                           5 to 7
2179                    Jeff Dunham: Controlled Chaos
2258                              Buddy Thunderstruck
2338                                      Grand Masti
2402       Beak & Brain: Genius Birds From Down Under
2410                               Love Is in the Air
2654                          Marco Luque: Tamo Junto
2655         Mr. Gaga: A True Story of Love and Dance
2895                              The Twins Effect II
3223                                      Case Closed
3313                                     Chelsea Does
3432                                       Camp X-Ray
3556                                          Save Me
3702                                 Hurricane Bianca
3877                                          Lincoln
4011         Cats & Dogs: The Revenge of Kitty Galore
4125                 Super Monsters and the Wish Star
4462    My Little Pony Equestria Girls: Rainbow Rocks
4495                                 Girls und Panzer
4729                                Tiny House Nation
4753      Baahubali 2: The Conclusion (Hindi Version)
4868                            Rust Valley Restorers
4904                                     Now and Then
4935                                           Héroes
4992                                   Cannon Busters
4993                      Chhota Bheem Kungfu Dhamaka
5099                                           Lechmi
5103                                       Mahabharat
5198                                          Amateur
5205                                             Troy
5230                                      Küçük Esnaf
5326              Patton Oswalt: Talking for Clapping
5390                                        21 & Over
5613                                         Quantico
5736                                The Dragon Prince
5857                                 Outback Truckers
5974                                             NCIS
5985                                       Marco Polo
6000                               Friday Night Tykes
6224                  Anthony Bourdain: Parts Unknown
Name: title, dtype: object

In [43]:
netflix.sort_values(by='imdb Rating',ascending = False)

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,imdb Rating
972,70153553,Harud,Aamir Bashir,"Mohammad Amir Naji, Shahnawaz Bhat, Shamim Bas...",India,"October 1, 2016",2010,TV-14,100 min,"Dramas, International Movies",A young Kashmiri man sets out to escape to Pak...,10.0
4390,80172145,Diablero,NaN,"Christopher Von Uckermann, Horacio García Roja...",Mexico,"December 21, 2018",2018,TV-MA,1 Season,"International TV Shows, Spanish-Language TV Sh...","When a young girl goes missing in a big city, ...",10.0
5894,80220541,Go! Live Your Way,NaN,"Pilar Pascual, Renata Toscano, José Giménez Za...",Argentina,"June 21, 2019",2019,TV-G,2 Seasons,"Kids' TV, Spanish-Language TV Shows, Teen TV S...",Charismatic Mía gets a scholarship to an elite...,10.0
3196,70142888,The Tourist,Florian Henckel von Donnersmarck,"Angelina Jolie, Johnny Depp, Paul Bettany, Tim...","United States, France, Italy, United Kingdom","January 7, 2020",2010,PG-13,103 min,"Action & Adventure, Romantic Movies",An American tourist seeking solace for his sha...,10.0
2862,80236236,Another Life,NaN,"Katee Sackhoff, Justin Chatwin, Samuel Anderso...",United States,"July 25, 2019",2019,TV-MA,1 Season,"TV Action & Adventure, TV Dramas, TV Mysteries","After a massive alien artifact lands on Earth,...",10.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1315,81034946,Maradona in Mexico,NaN,Diego Armando Maradona,"Argentina, United States, Mexico","November 13, 2019",2020,TV-MA,1 Season,"Docuseries, Spanish-Language TV Shows","In this docuseries, soccer great Diego Maradon...",0.0
3004,81145271,Black & Privileged: Volume 1,Mark Harris,"Dawnisha Halfkenny, Simeon Henderson, Corey He...",United States,"July 12, 2019",2019,TV-MA,79 min,Dramas,When low-income families move into a thriving ...,0.0
239,81018238,Samantaral,Partha Chakraborty,"Riddhi Sen, Parambrata Chatterjee, Soumitra Ch...",India,"September 15, 2018",2017,TV-MA,110 min,"Dramas, International Movies","On a family visit, a young man and his girlfri...",0.0
2622,80999727,Encerrados,NaN,"Luis Machín, Maria Merlino, Fabián Vena, Ana C...",NaN,"June 18, 2018",2018,TV-MA,1 Season,"International TV Shows, Spanish-Language TV Sh...",This fictional series tells the stories of wha...,0.0
688,81192594,Power Rangers Beast Morphers,NaN,"Rorrie D. Travis, Jazz Baduwalia, Jacqueline S...",United States,"October 15, 2019",2019,TV-Y7-FV,1 Season,Kids' TV,A new breed of secret agents must stop a ruthl...,0.0

In [45]:
netflix[(netflix['imdb Rating']>8) & (netflix['country']=='spain')]

Empty DataFrame
Columns: [show_id, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description, imdb Rating]
Index: []

In [46]:
netflix[netflix.isnull().any(axis=1)]

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,imdb Rating
1,80117401,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,3.5
2,70234439,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",2.5
3,80058654,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,5.5
5,80163890,Apaches,NaN,"Alberto Ammann, Eloy Azorín, Verónica Echegui,...",Spain,"September 8, 2017",2016,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",A young journalist is forced into a life of cr...,3.1
8,80117902,Fire Chasers,NaN,NaN,United States,"September 8, 2017",2017,TV-MA,1 Season,"Docuseries, Science & Nature TV","As California's 2016 fire season rages, brave ...",8.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil...",3.4
6230,70286564,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews...",2.7
6231,80116008,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...,0.1
6232,70281022,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ...",5.6
6233,70153404,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...,2.3

# Which items have missing values in any of the columns (Hint: use Logical Masking)

In [47]:
netflix[netflix.isnull().any(axis=1)]

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,imdb Rating
1,80117401,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,3.5
2,70234439,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",2.5
3,80058654,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,5.5
5,80163890,Apaches,NaN,"Alberto Ammann, Eloy Azorín, Verónica Echegui,...",Spain,"September 8, 2017",2016,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",A young journalist is forced into a life of cr...,3.1
8,80117902,Fire Chasers,NaN,NaN,United States,"September 8, 2017",2017,TV-MA,1 Season,"Docuseries, Science & Nature TV","As California's 2016 fire season rages, brave ...",8.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil...",3.4
6230,70286564,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews...",2.7
6231,80116008,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...,0.1
6232,70281022,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ...",5.6
6233,70153404,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...,2.3

In [48]:
netflix.dropna()

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,imdb Rating
0,81145628,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...,9.2
4,80125979,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...,3.5
6,70304989,Automata,Gabe Ibáñez,"Antonio Banderas, Dylan McDermott, Melanie Gri...","Bulgaria, United States, Spain, Canada","September 8, 2017",2014,R,110 min,"International Movies, Sci-Fi & Fantasy, Thrillers","In a dystopian future, an insurance adjuster f...",7.2
7,80164077,Fabrizio Copano: Solo pienso en mi,"Rodrigo Toro, Francisco Schultz",Fabrizio Copano,Chile,"September 8, 2017",2017,TV-MA,60 min,Stand-Up Comedy,Fabrizio Copano takes audience participation t...,7.9
9,70304990,Good People,Henrik Ruben Genz,"James Franco, Kate Hudson, Tom Wilkinson, Omar...","United States, United Kingdom, Denmark, Sweden","September 8, 2017",2014,R,90 min,"Action & Adventure, Thrillers",A struggling couple can't believe their luck w...,1.9
...,...,...,...,...,...,...,...,...,...,...,...,...
6142,80063224,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"August 30, 2019",2019,TV-PG,7 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...,2.6
6158,80164216,Miraculous: Tales of Ladybug & Cat Noir,Thomas Astruc,"Cristina Vee, Bryce Papenbrook, Keith Silverst...","France, South Korea, Japan","August 2, 2019",2018,TV-Y7,4 Seasons,"Kids' TV, TV Action & Adventure","When Paris is in peril, Marinette becomes Lady...",2.8
6167,80115328,Sacred Games,"Vikramaditya Motwane, Anurag Kashyap","Saif Ali Khan, Nawazuddin Siddiqui, Radhika Ap...","India, United States","August 15, 2019",2019,TV-MA,2 Seasons,"Crime TV Shows, International TV Shows, TV Dramas",A link in their pasts leads an honest cop to a...,1.2
6182,80176842,Men on a Mission,Jung-ah Im,"Ho-dong Kang, Soo-geun Lee, Sang-min Lee, Youn...",South Korea,"April 9, 2019",2019,TV-14,4 Seasons,"International TV Shows, Korean TV Shows, Stand...",Male celebs play make-believe as high schooler...,3.4
6213,80126599,Leyla and Mecnun,Onur Ünlü,"Ali Atay, Melis Birkan, Serkan Keskin, Ahmet M...",Turkey,"April 15, 2017",2014,TV-PG,3 Seasons,"International TV Shows, Romantic TV Shows, TV ...",Destiny brings Mecnun and Leyla together as ne...,6.9

In [49]:
netflix.fillna(value='not available')

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,imdb Rating
0,81145628,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...,9.2
1,80117401,Jandino: Whatever it Takes,not available,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,3.5
2,70234439,Transformers Prime,not available,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",2.5
3,80058654,Transformers: Robots in Disguise,not available,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,5.5
4,80125979,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,Red vs. Blue,not available,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,not available,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil...",3.4
6230,70286564,Maron,not available,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,not available,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews...",2.7
6231,80116008,Little Baby Bum: Nursery Rhyme Friends,not available,not available,not available,not available,2016,not available,60 min,Movies,Nursery rhymes and original music for children...,0.1
6232,70281022,A Young Doctor's Notebook and Other Stories,not available,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,not available,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ...",5.6
6233,70153404,Friends,not available,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,not available,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...,2.3